local util = require("tests.test_util")

describe("treesitter js", function()
  it("parses all symbols correctly", function()
    util.test_file_symbols("treesitter", "./tests/treesitter/js_test.js", {
      {
        kind = "Class",
        name = "Cl_1",
        level = 0,
        lnum = 1,
        col = 0,
        end_lnum = 4,
        end_col = 1,
        children = {
          {
            kind = "Method",
            name = "meth_1",
            level = 1,
            lnum = 2,
            col = 2,
            end_lnum = 2,
            end_col = 13,
          },
          {
            kind = "Method",
            name = "cl_fn_3",
            level = 1,
            lnum = 3,
            col = 2,
            end_lnum = 3,
            end_col = 20,
          },
        },
      },
      {
        kind = "Function",
        name = "fn_1",
        level = 0,
        lnum = 6,
        col = 0,
        end_lnum = 6,
        end_col = 18,
      },
      {
        kind = "Function",
        name = "describe UnitTest",
        level = 0,
        lnum = 8,
        col = 0,
        end_lnum = 20,
        end_col = 2,
        children = {
          {
            kind = "Function",
            name = "afterAll",
            level = 1,
            lnum = 9,
            col = 2,
            end_lnum = 9,
            end_col = 20,
          },
          {
            kind = "Function",
            name = "afterEach",
            level = 1,
            lnum = 10,
            col = 2,
            end_lnum = 10,
            end_col = 21,
          },
          {
            kind = "Function",
            name = "beforeAll",
            level = 1,
            lnum = 11,
            col = 2,
            end_lnum = 11,
            end_col = 21,
          },
          {
            kind = "Function",
            name = "beforeEach",
            level = 1,
            lnum = 12,
            col = 2,
            end_lnum = 12,
            end_col = 22,
          },
          {
            kind = "Function",
            name = "test should describe the test",
            level = 1,
            lnum = 13,
            col = 2,
            end_lnum = 13,
            end_col = 44,
          },
          {
            kind = "Function",
            name = "it is an alias for test",
            level = 1,
            lnum = 14,
            col = 2,
            end_lnum = 14,
            end_col = 38,
          },
          {
            kind = "Function",
            name = "test.skip skip this test",
            level = 1,
            lnum = 15,
            col = 2,
            end_lnum = 15,
            end_col = 39,
          },
          {
            kind = "Function",
            name = "test.todo this is a todo",
            level = 1,
            lnum = 16,
            col = 2,
            end_lnum = 16,
            end_col = 29,
          },
          {
            kind = "Function",
            name = "describe.each Test Suite",
            level = 1,
            lnum = 17,
            col = 2,
            end_lnum = 19,
            end_col = 4,
            children = {
              {
                kind = "Function",
                name = "test.each runs multiple times",
                level = 2,
                lnum = 18,
                col = 4,
                end_lnum = 18,
                end_col = 50,
              },
            },
          },
        },
      },
      {
        kind = "Function",
        name = "fn_2",
        level = 0,
        lnum = 22,
        col = 0,
        end_lnum = 22,
        end_col = 22,
      },
      {
        kind = "Function",
        name = "fn_3",
        level = 0,
        lnum = 23,
        col = 0,
        end_lnum = 23,
        end_col = 28,
      },
      {
        kind = "Function",
        name = "g",
        level = 0,
        lnum = 25,
        col = 0,
        end_lnum = 25,
        end_col = 16,
      },
      {
        kind = "Function",
        name = "g_1",
        level = 0,
        lnum = 26,
        col = 0,
        end_lnum = 26,
        end_col = 28,
      },
    })
  end)
end)
