local util = require("tests.test_util")

describe("treesitter lua", function()
  it("parses all symbols correctly", function()
    util.test_file_symbols("treesitter", "./tests/treesitter/lua_test.lua", {
      {
        kind = "Function",
        name = "fn_1",
        level = 0,
        lnum = 1,
        col = 0,
        end_lnum = 3,
        end_col = 3,
      },
      {
        kind = "Function",
        name = "fn_2",
        level = 0,
        lnum = 5,
        col = 0,
        end_lnum = 7,
        end_col = 3,
      },
      {
        kind = "Function",
        name = "fn_3",
        level = 0,
        lnum = 9,
        col = 0,
        end_lnum = 11,
        end_col = 3,
      },
      {
        kind = "Function",
        name = "fn_4",
        level = 0,
        lnum = 13,
        col = 0,
        end_lnum = 18,
        end_col = 3,
        children = {
          {
            kind = "Function",
            name = "<Anonymous>",
            level = 1,
            lnum = 14,
            col = 7,
            end_lnum = 16,
            end_col = 5,
          },
        },
      },
      {
        kind = "Function",
        name = "meth_1",
        level = 0,
        lnum = 21,
        col = 2,
        end_lnum = 23,
        end_col = 5,
      },
      {
        kind = "Function",
        name = "M.fn_5",
        level = 0,
        lnum = 26,
        col = 0,
        end_lnum = 26,
        end_col = 23,
      },
      {
        kind = "Function",
        name = "M.fn_6",
        level = 0,
        lnum = 27,
        col = 0,
        end_lnum = 27,
        end_col = 21,
      },
      {
        kind = "Function",
        name = "describe UnitTest",
        level = 0,
        lnum = 29,
        col = 0,
        end_lnum = 33,
        end_col = 4,
        children = {
          {
            kind = "Function",
            name = "before_each",
            level = 1,
            lnum = 30,
            col = 2,
            end_lnum = 30,
            end_col = 29,
          },
          {
            kind = "Function",
            name = "after_each",
            level = 1,
            lnum = 31,
            col = 2,
            end_lnum = 31,
            end_col = 28,
          },
          {
            kind = "Function",
            name = "it describes the test",
            level = 1,
            lnum = 32,
            col = 2,
            end_lnum = 32,
            end_col = 42,
          },
        },
      },
      {
        kind = "Function",
        name = "describe UnitTest",
        level = 0,
        lnum = 35,
        col = 0,
        end_lnum = 39,
        end_col = 4,
        children = {
          {
            kind = "Function",
            name = "before_each",
            level = 1,
            lnum = 36,
            col = 2,
            end_lnum = 36,
            end_col = 31,
          },
          {
            kind = "Function",
            name = "after_each",
            level = 1,
            lnum = 37,
            col = 2,
            end_lnum = 37,
            end_col = 30,
          },
          {
            kind = "Function",
            name = "it describes the test",
            level = 1,
            lnum = 38,
            col = 2,
            end_lnum = 38,
            end_col = 44,
          },
        },
      },
      {
        kind = "Function",
        name = "M:fn_7",
        level = 0,
        lnum = 41,
        col = 0,
        end_lnum = 41,
        end_col = 21,
      },
      {
        kind = "Function",
        name = 'M["fn_8"]',
        level = 0,
        lnum = 43,
        col = 0,
        end_lnum = 43,
        end_col = 26,
      },
    })
  end)
end)
