local util = require("tests.test_util")

describe("treesitter solidity", function()
  it("parses all symbols correctly", function()
    util.test_file_symbols("treesitter", "./tests/treesitter/solidity_test.sol", {
      {
        kind = "Module",
        name = "a",
        level = 0,
        lnum = 5,
        col = 0,
        end_lnum = 9,
        end_col = 1,
        children = {
          {
            kind = "Function",
            name = "f",
            level = 1,
            lnum = 6,
            col = 4,
            end_lnum = 8,
            end_col = 5,
          },
        },
      },
      {
        kind = "Class",
        name = "A",
        level = 0,
        lnum = 11,
        col = 0,
        end_lnum = 25,
        end_col = 1,
        children = {
          {
            kind = "Field",
            name = "flag",
            level = 1,
            lnum = 12,
            col = 9,
            end_lnum = 12,
            end_col = 13,
          },
          {
            kind = "Event",
            name = "Log",
            level = 1,
            lnum = 13,
            col = 4,
            end_lnum = 13,
            end_col = 54,
          },
          {
            kind = "Constructor",
            name = "constructor",
            level = 1,
            lnum = 15,
            col = 4,
            end_lnum = 15,
            end_col = 27,
          },
          {
            kind = "Method",
            name = "m",
            level = 1,
            lnum = 17,
            col = 4,
            end_lnum = 19,
            end_col = 5,
          },
          {
            kind = "Method",
            name = "never",
            level = 1,
            lnum = 21,
            col = 4,
            end_lnum = 24,
            end_col = 5,
          },
        },
      },
      {
        kind = "Interface",
        name = "I",
        level = 0,
        lnum = 27,
        col = 0,
        end_lnum = 29,
        end_col = 1,
        children = {
          {
            kind = "Function",
            name = "f",
            level = 1,
            lnum = 28,
            col = 4,
            end_lnum = 28,
            end_col = 17,
          },
        },
      },
      {
        kind = "Struct",
        name = "S",
        level = 0,
        lnum = 31,
        col = 0,
        end_lnum = 34,
        end_col = 1,
      },
      {
        kind = "Enum",
        name = "E",
        level = 0,
        lnum = 36,
        col = 0,
        end_lnum = 40,
        end_col = 1,
      },
    })
  end)
end)
